### PR TITLE
Add prettier again

### PR DESCRIPTION
**Pull request by PuneetGopinath**
Sorry @Andre601, plz mention why did you remove the build.yml, if it was because of many new lines, then I fixed the maximum line length in this pr.

By fixing the maximum line length, it will not add many new lines.

### CODE REVIEW

**Comment by Andre601** [comment]
The issue is that it f.e. made this
```html
<meta name="twitter:image" content="https://readme-workflows.github.io/assets/img/favicon.png">
```

into this
```html
<meta
    name="twitter:image"
    content="https://readme-workflows.github.io/assets/img/favicon.png"
/>
```

This is pointless and not even good to look at imo. Additionally is the `/>` pointless on pretty much all the cases.
We really don't need a action to make HTML "pretty". Its a waste of time since the goal of HTML code is not to look pretty but to function.

**Comment by PuneetGopinath** [comment]
Ok, then I will set it to make only CSS beauty, then it will be fine?

**Comment by Andre601** [comment]
> Ok, then I will set it to make only CSS beauty, then it will be fine?

I guess... I personally see no reason to have this in the first place. Only causes extra commits for no added benefits.

**Comment by PuneetGopinath** [comment]
> > Ok, then I will set it to make only CSS beauty, then it will be fine?
> 
> I guess... I personally see no reason to have this in the first place. Only causes extra commits for no added benefits.

It will not commit, if already beautiful

**Comment by PuneetGopinath** [comment]
I also forgot to say that it will also beautify JSON

**Review by Andre601 — APPROVED** [review]

**Comment by PuneetGopinath** [comment]
@abhijoshi2k Plz review

**Comment by PuneetGopinath** [comment]
@abhijoshi2k Plz review

**Pull request merged**
